### PR TITLE
Add ability to set tag name via env var for no prompt deploys

### PR DESCRIPTION
**Pull request by kcampos**

### CODE REVIEW

**Comment by bogdanRada** [comment]
@technicalpickles, is this still needed? This pull request seems to be stale. I could make the changes for current version to support this if you think is a good thing.

**Comment by technicalpickles** [comment]
@bogdanRada I haven't used this in awhile, so it's hard to say. The main benefit is to be able to specify the tag to use from the command line without an interactive prompt

**Comment by kcampos** [comment]
It's certainly a needed feature if you are trying to use this with any
automation.

**Comment by bogdanRada** [comment]
@kcampos can you rebase your changes with master branch? There was a lot changes since you opened this PR

**Comment by bogdanRada** [comment]
since there was no response for two weeks now, i added it myself in this commit: 39ee3de7ef55ac1941ed3057f492c148bc9e6f3c .

**Comment by bogdanRada** [comment]
Released 1.5.5 version

**Pull request closed without merging**
